#!/bin/bash

# Run a Helm unit test using the 'helm-unittest' Helm plugin.
# Reference: https://github.com/quintush/helm-unittest/blob/master/DOCUMENT.md

if [[ ! "$(helm plugin list | awk '/^unittest\t/{print $1}')" ]]; then
    echo "Installing 'helm-unittest' Helm plugin"
    helm plugin install https://github.com/quintush/helm-unittest
fi

helm unittest .
