#!/bin/bash

# TODO: Make deletion of Helm release at start of script configurable.
# TODO: Use environment variables for chart settings so that we can
#       use Summon to set these values in CI.
#
# Usage:
#     ./test-helm [<Helm test release>]
#
# Example:
#     ./test-helm my-test-release

helm_release="${1:-helm-test-release}"
helm delete "$helm_release"
sleep 6
helm install "$helm_release" . \
     --set conjur.account="myConjurAccount" \
     --set conjur.applianceUrl="https://conjur-oss.conjur-oss.svc.cluster.local" \
     --set conjur.ssl.certificateFile="files/conjur-cert.pem" \
     --set authnK8s.authenticatorID="my-authenticator-id"

helm test "$helm_release" --logs
